version: "3.9"
services: 
    artists-api:
        build: ../solutions/artists-backend/artists
        ports:
        - "5001:80"
        environment: 
            - MSSQL_SERVER=artists-mssql
            - MSSQL_USERNAME=sa
            - MSSQL_PASSWORD=secret@456
            - MSSQL_DATABASE=master
        depends_on: 
            - artists-mssql
    artist-works-api:
        build: ../solutions/artist-works-backend/artist-works
        ports:
        - "5002:5002"
        depends_on: 
            - artist-works-mongodb
    artists-nginx:
        build: ../solutions/nginx
        ports:
        - "8080:8080"
        depends_on: 
            - artist-works-api
            - artists-api
    artists-webapp:
        build: ../solutions/artists-frontend
        ports:
        - "4200:4200"
        depends_on: 
            - artists-nginx
    artist-works-mongodb:
        image: mongo
        ports:
        - "27017:27017"
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=mongo
            - MONGO_INITDB_ROOT_PASSWORD=secret@123
    artists-mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - "1433:1433"
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=secret@456
