version: "3.9"
services: 
    artists-api:
        build: ../solutions/artists-backend/artists
        ports:
        - "5001:80"
        networks:
        - my-network-svc
    artist-works-api:
        build: ../solutions/artist-works-backend/artist-works
        ports:
        - "5002:5002"
        networks:
        - my-network-svc
    artists-nginx:
        build: ../solutions/nginx
        ports:
        - "8080:8080"
        networks:
        - my-network-svc
    artists-webapp:
        build: ../solutions/artists-frontend
        ports:
        - "4200:4200"
        networks:
        - my-network-svc
networks:
    my-network-svc:
        external: true
        driver: bridge