version: "3.9"
services: 
    artists-api:
        build: ../solutions/artists-backend/artists
        ports:
        - "5001:80"
    artist-works-api:
        build: ../solutions/artist-works-backend/artist-works
        ports:
        - "5002:5002"
        depends_on: 
            - artist-works-mongodb
    artists-nginx:
        build: ../solutions/nginx
        ports:
        - "8080:8080"
        depends_on: 
            - artist-works-api
            - artists-api
    artists-webapp:
        build: ../solutions/artists-frontend
        ports:
        - "4200:4200"
        depends_on: 
            - artists-nginx
    artist-works-mongodb:
        image: mongo
        ports:
        - "27017:27017"
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=mongo
            - MONGO_INITDB_ROOT_PASSWORD=secret@123
