# filebeat.inputs:
# - type: log
#   enabled: true
#   paths:
#     - /var/log/*.log

filebeat.modules:
# Nginx Module to consume to access and error logs from mounted volume
- module: nginx
  access:
    var.paths: ["/var/log/nginx/access.log*"]
  error:
    var.paths: ["/var/log/nginx/error.log*"]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "changeme"

setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "changeme"
  