version: "3.9"
services: 
    elasticsearch:
        build:
            context: elasticsearch/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            - type: bind
              source: ./elasticsearch/config/elasticsearch.yml
              target: /usr/share/elasticsearch/config/elasticsearch.yml
              read_only: true
            - type: volume
              source: elasticsearch
              target: /usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
            ELASTIC_PASSWORD: changeme
            discovery.type: single-node
        networks:
            - elasticstack-network-svc
    
    logstash:
        build:
            context: logstash/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            - type: bind
              source: ./logstash/config/logstash.yml
              target: /usr/share/logstash/config/logstash.yml
              read_only: true
            - type: bind
              source: ./logstash/pipeline
              target: /usr/share/logstash/pipeline
              read_only: true
        ports:
            - "5000:5000"
            - "9600:9600"
        expose: 
            - "5044"
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - elasticstack-network-svc
        depends_on:
            - elasticsearch

    kibana:
        build:
            context: kibana/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            - type: bind
              source: ./kibana/config/kibana.yml
              target: /usr/share/kibana/config/kibana.yml
              read_only: true
        ports:
            - "5601:5601"
        networks:
            - elasticstack-network-svc
        depends_on:
            - elasticsearch

    filebeat:
        build:
            context: filebeat/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            - type: bind
              source: ./filebeat/config/filebeat.yml
              target: /usr/share/filebeat/filebeat.yml
              read_only: true            
        # environment: 
        #     setup.kibana.host: kibana:5601
            # output.elasticsearch.hosts: 
            #     elasticsearch:9200
        networks:
            - elasticstack-network-svc
        depends_on:
            - elasticsearch

networks:
  elasticstack-network-svc:
    external: true
    name: my-network-svc

volumes:
  elasticsearch:
